interface AppSettings {
  ACCESS_TOKEN_DURATION_MINUTES: number;
  REFRESH_TOKEN_DURATION_MINUTES: number;
  PASSWORD_RESET_TOKEN_DURATION_MINUTES: number;
  EMAIL_VERIFICATION_TOKEN_DURATION_MINUTES: number;
  REFRESH_TOKEN_COOKIE_NAME: string;
  REFRESH_TOKEN_COOKIE_SAME_SITE: 'strict' | 'lax' | 'none';
  EMAIL_RATE_LIMIT_WINDOW_MS: number;
  EMAIL_RATE_LIMIT_MAX_REQUESTS: number;
  AUTH_RATE_LIMIT_WINDOW_MS: number;
  AUTH_RATE_LIMIT_MAX_REQUESTS: number;
  GENERAL_RATE_LIMIT_WINDOW_MS: number;
  GENERAL_RATE_LIMIT_MAX_REQUESTS: number;
  GUEST_RATE_LIMIT_WINDOW_MS: number;
  GUEST_RATE_LIMIT_MAX_REQUESTS: number;
  UPLOAD_RATE_LIMIT_WINDOW_MS: number;
  UPLOAD_RATE_LIMIT_MAX_REQUESTS: number;
  PENDING_UPLOADS_CLEANUP_CUTOFF_MS: number;
  RECONCILE_FOLLOW_COUNTERS_CRON: string;
  IMAGE_FILE_SIZE_LIMIT_BYTES: number;
  VIDEO_FILE_SIZE_LIMIT_BYTES: number;
  PRESIGNED_UPLOAD_URL_EXPIRY_SECONDS: number;
  STORAGE_QUOTA_FREE_BYTES: number;
  POST_ALLOWED_CONTENT_TYPES: readonly string[];
  AVATAR_POST_ALLOWED_CONTENT_TYPES: readonly string[];
}

const settings: AppSettings = {
  ACCESS_TOKEN_DURATION_MINUTES: 1, // We can increse after test
  REFRESH_TOKEN_DURATION_MINUTES: 10_080,
  PASSWORD_RESET_TOKEN_DURATION_MINUTES: 15,
  EMAIL_VERIFICATION_TOKEN_DURATION_MINUTES: 1440,
  REFRESH_TOKEN_COOKIE_NAME: 'nexora-refresh-token',
  REFRESH_TOKEN_COOKIE_SAME_SITE: 'none',
  EMAIL_RATE_LIMIT_WINDOW_MS: 900000,
  EMAIL_RATE_LIMIT_MAX_REQUESTS: 5,
  AUTH_RATE_LIMIT_WINDOW_MS: 60000,
  AUTH_RATE_LIMIT_MAX_REQUESTS: 10,
  GENERAL_RATE_LIMIT_WINDOW_MS: 60000,
  GENERAL_RATE_LIMIT_MAX_REQUESTS: 200,
  GUEST_RATE_LIMIT_WINDOW_MS: 60000,
  GUEST_RATE_LIMIT_MAX_REQUESTS: 60,
  UPLOAD_RATE_LIMIT_WINDOW_MS: 600000,
  UPLOAD_RATE_LIMIT_MAX_REQUESTS: 20,
  PENDING_UPLOADS_CLEANUP_CUTOFF_MS: 60 * 60 * 1000, // 1 hour
  RECONCILE_FOLLOW_COUNTERS_CRON: '0 3 * * *',
  IMAGE_FILE_SIZE_LIMIT_BYTES: 10 * 1024 * 1024, // 10 MB
  VIDEO_FILE_SIZE_LIMIT_BYTES: 200 * 1024 * 1024, // 200 MB
  PRESIGNED_UPLOAD_URL_EXPIRY_SECONDS: 900, // 15 minutes
  STORAGE_QUOTA_FREE_BYTES: 20 * 1024 * 1024, // 20 MB
  POST_ALLOWED_CONTENT_TYPES: ['image/jpeg', 'image/png', 'image/gif', 'image/webp', 'video/mp4', 'video/webm'],
  AVATAR_POST_ALLOWED_CONTENT_TYPES: ['image/jpeg', 'image/png', 'image/webp'],
};

export default settings;
